name = "RemoteS"
uuid = "26020ff4-e92a-488e-a723-09c28e89e04a"
authors = ["Joaquim Luis <jmfluis@gmail.com>"]
version = "1.2.1"

[deps]
GMT = "5752ebe1-31b9-557e-87aa-f909b540aa54"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Dates  = "ade2ca70-3891-5945-98fb-dc099432e06a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"

[weakdeps]
SatelliteToolboxTle = "7ff27aeb-5fff-4337-a9ee-a9fe6b7ed35e"
SatelliteToolboxPropagators = "c2b69894-ea78-4e2b-9ba6-cedbbc3d14d7"
SatelliteToolboxTransformations = "6b019ec1-7a1e-4f04-96c7-a9db1ca5514d"

[extensions]
RemoteSSatTbxExt = ["SatelliteToolboxTle", "SatelliteToolboxPropagators", "SatelliteToolboxTransformations"]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SatelliteToolboxTle = "7ff27aeb-5fff-4337-a9ee-a9fe6b7ed35e"
SatelliteToolboxPropagators = "c2b69894-ea78-4e2b-9ba6-cedbbc3d14d7"
SatelliteToolboxTransformations = "6b019ec1-7a1e-4f04-96c7-a9db1ca5514d"

[targets]
test = ["Test"]

[compat]
julia = "1.9"
GMT = "1.9"
PrecompileTools = "1.0"
SatelliteToolboxTle = "1"
SatelliteToolboxPropagators = "0.3"
SatelliteToolboxTransformations = "0.1"
DecisionTree = "0.12"
